export const WEATHER_FORECAST_DATA_FOR_GEOLOCATION = "WEATHER_FORECAST_DATA_FOR_GEOLOCATION";
export const WEATHER_FORECAST_DATA_FOR_SITY_NAME = "WEATHER_FORECAST_DATA_FOR_SITY_NAME";
export const USER_LOCATION_FOR_IP = "USER_LOCATION_FOR_IP";