export const WEATHER_FORECAST_DATA_FOR_GEOLOCATION = 'WEATHER_FORECAST_DATA_FOR_GEOLOCATION';
export const WEATHER_FORECAST_DATA_FOR_SITY_NAME = 'WEATHER_FORECAST_DATA_FOR_SITY_NAME';
export const USER_LOCATION_FOR_IP = 'USER_LOCATION_FOR_IP';
export const WEATHER_FOR_WEEK = 'WEATHER_FOR_WEEK';
export const WEATHER_HISTORY = 'WEATHER_HISTORY';
export const WEATHER_HOURLY = 'WEATHER_HOURLY';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const GET_AIR_POLLUTION = 'GET_AIR_POLLUTION';
